(define (assert expected given)
    (if (eq? given expected)
        (begin
            (display pass)
            (newline)
        )
        (begin
            (display "ASSERTION FAILURE: ")
            (display "was given ")
            (display given)
            (display " but expected ")
            (display expected)
            (newline)
        )
    )
)
